### ISSUE TITLE
安装完后没有桌面程序 根目录也没有找到可以打开的程序

### ISSUE THREAD

**Issue by MuHei-del** [JamXi233/WaveTools#10]
桌面没有快捷方式 去根目录找也没找到 
关掉后都不知道要怎么打开了

**Comment by JamXi233** [comment]
在开始菜单中可以打开

**Comment by MuHei-del** [comment]
> 在开始菜单中可以打开

谢谢 找到了
开始菜单好久都没用过了
还是建议加个快捷方式或者在搜索里面能搜索到吧
