### ISSUE TITLE
修复了吗

### ISSUE THREAD

**Issue by fufumo** [JamXi233/WaveTools#12]
![image](https://github.com/JamXi233/WaveTools/assets/137279673/d0bd7b99-03e7-4430-aa35-cd0524708639)

**Comment by JamXi233** [comment]
非工具箱会导致的问题，请检查电脑环境。

**Comment by fufumo** [comment]
重启没有办法

**Comment by fufumo** [comment]
难道要打开启动器启动

**Comment by JamXi233** [comment]
这个自行解决，非工具箱问题
如果官方启动器也不能启动，基本就是系统环境问题

**Comment by fufumo** [comment]
啊这，官方启动器可以

**Comment by fufumo** [comment]
没有log如何下手解决

**Comment by JamXi233** [comment]
是官方还是WeGame

**Comment by fufumo** [comment]
肯定官方啊
