### ISSUE TITLE
.NET 安装失败

### ISSUE THREAD

**Issue by link-fgfgui** [JamXi233/WaveTools#13]
![image](https://github.com/JamXi233/WaveTools/assets/96362154/303e1d03-9d3e-43a6-be23-b1d68111f6b9)

**Comment by JamXi233** [comment]
https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-7.0.15-windows-x64-installer
尝试手动下载安装

**Comment by link-fgfgui** [comment]
电脑本身装了.net，下release里的安装包也能安装，但是如果走安装程序就会卡这里
