### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by TomyJan** [JamXi233/WaveTools#14]
![image](https://github.com/JamXi233/WaveTools/assets/67973160/7794217b-ab24-4eda-8128-8f71c2ff5227)
可能是 OneDrive 目录带空格的锅? 大佬能否做下兼容

另询问一下, 工具箱导出的抽卡记录是否是标准的 UIGF 格式, 因为我这边再做个项目, 想要和工具箱兼容

**Comment by TomyJan** [comment]
啊, 用离线包可以安装了, 原来还没做抽卡记录的导入导出
这里催更下抽卡链接的导出

**Comment by TomyJan** [comment]
注意到 wwgf 很多字段和 uigf 出入较大, 比如没有 info.export_time, list 中多了 gacha_id 而且长度很长是在为什么东西预留吗()
请问格式还会改动或者这已经几乎是最终形态了

**Comment by JamXi233** [comment]
格式上基本不会改动了
可以说目前的抽卡导出与SRGF比较类似
