### ISSUE TITLE
增加启动参数

### ISSUE THREAD

**Issue by Future-FoXe** [JamXi233/WaveTools#15]
希望在开始游戏栏增加启动参数项，想无边框启动
[https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html](url)

**Comment by JamXi233** [comment]
UE4引擎而非Unity引擎

**Comment by xuan06zyx** [comment]
这大概跟引擎没关系，类似图中这样给快捷方式添加参数，应该不难（？）
![Uploading 060807904e8fd42d6857c8590374a84b.png…]()

**Comment by xuan06zyx** [comment]
starward是有这个功能的
![QQ截图20240617170016](https://github.com/JamXi233/WaveTools/assets/126635659/77cacd08-5146-4c3a-86d3-6862fe77c597)

**Comment by JamXi233** [comment]
@xuan06zyx 
我认为他的意思应该是按照Unity官方文档的参数添加一些启动项，而非仅添加[启动参数]功能。
@Future-FoXe 
是否只是想添加[启动参数]功能？

**Comment by Future-FoXe** [comment]
> 我认为他的意思应该是按照Unity官方文档的参数添加一些启动项，而非仅添加[启动参数]功能。 是否只是想添加[启动参数]功能？
@JamXi233灵感来源确实是Starward，希望能实现相同的功能（还有它的其它功能），我之前对鸣潮尝试过
 @xuan06zyx 的方法发现无效，于是发布了该议题，那看来是‘_UE4引擎而非Unity引擎_’的原因？
如果添加‘启动项/启动参数’无法实现游戏无边框启动，那么我将不再申请添加[启动参数]功能

**Comment by xuan06zyx** [comment]
我个人刚好需要这个功能 看了眼issues发现有人提出过类似问题便在此回复了

**Comment by JamXi233** [comment]
[WaveTools_1.1.6.0](https://github.com/JamXi233/WaveTools/releases/tag/1.1.6.0)已添加该功能
