### ISSUE TITLE
开始页面在屏幕上的位置不对

### ISSUE THREAD

**Issue by SD003XX** [JamXi233/WaveTools#16]
正如您所看到的那样
![屏幕截图 2024-06-04 141941](https://github.com/JamXi233/WaveTools/assets/171657174/3a90f3bf-61a0-4fc9-8fe8-2071b5fcb21c)
它的位置不对

感谢您为⌈鸣潮⌋所作出的贡献

**Comment by JamXi233** [comment]
请问您的分辨率和缩放分别是多少？
