### ISSUE TITLE
请求：给抽卡记录五星加上出货抽数

### ISSUE THREAD

**Issue by cyf5119** [JamXi233/WaveTools#17]
希望能在抽卡记录详情里给五星加上抽出时花费的抽数，且按照时间排列，类似下图效果。
（柱状图无需求）
谢谢！
![image](https://github.com/JamXi233/WaveTools/assets/89454904/8ea8ef10-b035-479b-a137-5aae33369ca2)

**Comment by JamXi233** [comment]
![image](https://github.com/JamXi233/WaveTools/assets/38126613/2551d23a-be4d-4190-8d4f-2d04083ab332)
已经在做了，在下一版本会推出

**Comment by fufumo** [comment]
火速吧
