### ISSUE TITLE
PowerShell方式安装程序后再启动闪退

### ISSUE THREAD

**Issue by Nathcuya** [JamXi233/WaveTools#20]
使用PowerShell方式安装后，仅在安装成功时显示了程序及其功能页面。第一次退出后再寻找软件打开**会闪退**，不能进入程序页面，使用管理员权限打开也不行。
并且在**Releases**中下载的安装程序被系统提示没有证书，**无法安装**。
后面又尝试了一下，发现在软件本体目录下启动会闪退，而**msix**程序再次点击打开时点击启动可以打开工具箱。
但在使用过程中发现无法识别和登录到账号，也无法使用抽卡分析功能，仅相当于一个帧率修改及游戏启动器（但帧率修改注册表也能实现啊）
**备注：我的账号是国际服亚服账号，不知国服账号能否使用**

**Comment by JamXi233** [comment]
1、当前版本工具箱未专门对国际服做支持，仅完整支持国服。
2、是否在开始菜单中打开的程序？如果是则转到第3条。
3、是否在目录**[文档\JSG-LLC\Logs]**中可以找到**[WaveTools_Log_最新日期]**日志文件？如果可以请上传上来。

**Comment by JamXi233** [comment]
已经超过两周没有收到您的回复，将关闭该issue。
