### ISSUE TITLE
[Feature request] 更换侧边栏抽卡记录图标

### ISSUE THREAD

**Issue by YCR160** [JamXi233/WaveTools#26]
感觉 SpecialEffectSize 比 FavoriteStar 更适合作为抽卡图标？

![image](https://github.com/JamXi233/WaveTools/assets/91136998/0ad970ee-bba9-42c0-9b65-9d7832393f6f)

![image](https://github.com/JamXi233/WaveTools/assets/91136998/c534da89-9a19-4f7f-a576-1d3fb1861e77)

<https://github.com/JamXi233/WaveTools/blob/6b71975a39713b99e314cce3f99263bec528a0ff/WaveTools/MainWindow.xaml#L42-L46>

**Comment by JamXi233** [comment]
[WaveTools_1.1.3.0](https://github.com/JamXi233/WaveTools/releases/tag/1.1.3.0)已更新
**已更换抽卡分析图标**
