### ISSUE TITLE
安装报错证书不受信任

### ISSUE THREAD

**Issue by SurpassIllusion** [JamXi233/WaveTools#3]
通过URL进行安装 
Add-AppxPackage : Deployment failed with HRESULT: 0x800B0109,
已处理证书链，但是在不受信任提供程序信任的根证书中终止。
错误 0x800B0109: 应用包或捆绑包中的签名的根证书必须是受信任的证书。
NOTE: For additional information, look for [ActivityId]
cde8664b-ae77-0004-e45c-edcd77aeda01 in the Event Log or use th
e command line Get-AppPackageLog -ActivityID cde8664b-ae77-0004-e45c-edcd77aeda01
At line:1 char:1
+ Add-AppxPackage -Path D:\Users\Documents\JSG-LLC\WaveTools\Installer\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (D:\Users\Docume....0.0.0_x64.msix:String)
[Add-AppxPackage], Exception
    + FullyQualifiedErrorId :
DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by JamXi233** [comment]
感谢您的反馈
问题现已修复，可再次使用Powershell进行安装。
