### ISSUE TITLE
已經開啟喚取紀錄仍無法獲取資料

### ISSUE THREAD

**Issue by SSB-ARFCN** [JamXi233/WaveTools#31]
如圖
![image](https://github.com/user-attachments/assets/9d3ac994-031b-487a-a623-669c3d1059bb)

**Comment by JamXi233** [comment]
游戏是国服还是国际服？

**Comment by SSB-ARFCN** [comment]
國際服的 歐洲伺服器

**Comment by JamXi233** [comment]
暂未专门对国际服支持
目前仅完整支持国服

**Comment by liu-yipeng** [comment]
哥 啥时候支持国际服

**Comment by JamXi233** [comment]
@liu-yipeng 暂时没有支持国际服的计划，如果以后更多人有需要才会加入支持。
