### ISSUE TITLE
无法验证发布者证书

### ISSUE THREAD

**Issue by nanami1993** [JamXi233/WaveTools#32]
![屏幕截图 2024-07-16 014652](https://github.com/user-attachments/assets/00aed082-3a7d-47da-8ea0-726364aecbfa)
发布者证书咋回事啊？

**Comment by JamXi233** [comment]
如果坚持使用Msix安装而不使用Powershell安装
则需要手动将证书安装到[受信任的根证书颁发机构]中

**Comment by nanami1993** [comment]
> 如果坚持使用Msix安装而不使用Powershell安装 则需要手动将证书安装到[受信任的根证书颁发机构]中

![屏幕截图 2024-07-16 020204](https://github.com/user-attachments/assets/dde9afc4-09ff-40a8-b04c-5b8960968136)
证书搞定了，这个咋搞

**Comment by nanami1993** [comment]
> > 如果坚持使用Msix安装而不使用Powershell安装 则需要手动将证书安装到[受信任的根证书颁发机构]中
> 
> ![屏幕截图 2024-07-16 020204](https://private-user-images.githubusercontent.com/141377243/348808967-dde9afc4-09ff-40a8-b04c-5b8960968136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjY5MzIsIm5iZiI6MTcyMTA2NjYzMiwicGF0aCI6Ii8xNDEzNzcyNDMvMzQ4ODA4OTY3LWRkZTlhZmM0LTA5ZmYtNDBhOC1iMDRjLTViODk2MDk2ODEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxODAzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmE4YzgyOWI3YjE4MTBhNmQ3ZjUxMmE1ZDY4NjVkNWUxZTk5MDRlNDNhNThlMGMzMGU0N2M2MGM3NmM3NGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mpkHz1t72ASqlaC0OC99RsDYSGrTZf6UWsWBx957-ZY)证书搞定了，这个咋搞

搞定了，感谢

**Comment by JamXi233** [comment]
https://download.visualstudio.microsoft.com/download/pr/00f765dd-f009-41b4-921f-bee1273f3638/3cb6ac95b2aa7eeb272c6179d56fd036/windowsdesktop-runtime-7.0.15-win-x64.exe
下载.NET运行库并安装
