### ISSUE TITLE
画质更改失效

### ISSUE THREAD

**Issue by sweet-de-way** [JamXi233/WaveTools#35]
鸣潮不再从 LocalStorage 和 GameUserSettings 文件中读取设置。

**Comment by JamXi233** [comment]
画质修改经测试目前没有问题
该Issue将被关闭

**Comment by sweet-de-way** [comment]
私密马赛😭，我犯了非常愚蠢的错误。
我一直用sqlite挂载着数据库，导致了游戏不能写入数据。
🙇‍♂️🙇‍♀️🙇‍♂️🙇‍♀️
