### ISSUE TITLE
现在启动器会触发ACE反作弊

### ISSUE THREAD

**Issue by Yanshao-ria** [JamXi233/WaveTools#36]
如题，今天玩的时候发现在深塔中帧数会重新锁回60，重新使用启动器修改帧数上限启动后，游戏要求重新登录账号，随后进入游戏加载完成后出现ACE反作弊弹窗并且强制退出游戏
![QQ截图20240721010738](https://github.com/user-attachments/assets/6bcce0d5-7852-4bd1-b538-cc1e97d11110)

**Comment by SSB-ARFCN** [comment]
啊？ 號還在嗎？

**Comment by Yanshao-ria** [comment]
号没事，把工具箱关了用官方启动器开游戏就行了，官方启动器开游戏大世界120帧还在。

**Comment by Yanshao-ria** [comment]
> 啊？ 號還在嗎？

号没事，把工具箱关了用官方启动器开游戏就行了，官方启动器开游戏大世界120帧还在。

**Comment by JamXi233** [comment]
画质修改仅修改本地数据库文件，并不对游戏内存进行修改。
