### ISSUE TITLE
显示分辨率问题

### ISSUE THREAD

**Issue by honestman9981** [JamXi233/WaveTools#39]
开发者你好，请问这个软件是不能调整窗口大小吗？还是只能固定1080P窗口
<img width="1679" alt="屏幕截图 2024-07-24 131446" src="https://github.com/user-attachments/assets/25f25efe-b12a-49e1-bbfa-d0db1593ad4a">

我4k显示器下 显得窗口很小
可以提供解决方法吗

**Comment by JamXi233** [comment]
软件本身设计为不可[最大化/调节窗口大小]
窗口大小跟随系统缩放
目前只能通过**调节系统缩放**来解决您的问题
