### ISSUE TITLE
更新后打开报错

### ISSUE THREAD

**Issue by 1432647** [JamXi233/WaveTools#4]
更新依赖后重启工具箱报错
[WaveTools_Panic_20240525_191240.zip](https://github.com/JamXi233/WaveTools/files/15443160/WaveTools_Panic_20240525_191240.zip)

**Comment by JamXi233** [comment]
尝试在设置中**按住Shift**点击检查依赖更新-强制重装-重启工具箱

**Comment by 1432647** [comment]
<img width="757" alt="88bf587703cc1b33971ac5c7339e8d5" src="https://github.com/JamXi233/WaveTools/assets/170803245/f7d69fc7-3c0f-4d1a-9815-c46797bf525c">
强制重装后仍会弹出该报错，尝试卸载软件重装后仍会弹出

**Comment by JamXi233** [comment]
好的 正在排查问题

**Comment by JamXi233** [comment]
是官方API的问题，现已修复，目前已可以正常使用。

**Comment by 1432647** [comment]
感谢您的付出，十元赞助愿您能走得更久

**Comment by JamXi233** [comment]
感谢您的慷慨赞助
