### ISSUE TITLE
获取不到抽卡记录

### ISSUE THREAD

**Issue by Cedarflash** [JamXi233/WaveTools#42]
可能是我安装时出了什么问题或者不小心改了什么设置吧，我的抽卡记录只能在这个路径里才能找到：
Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\ThirdParty\KrPcSdk_Mainland\KRSDKRes\KRSDKWebView\debug.log
这个路径里找不到：
Wuthering Waves\Wuthering Waves Game\Client\Saved\Logs\Client.log 
用工具箱一直获取不到抽卡记录，在debug.log文件里能手动搜到抽卡记录链接并在浏览器里查看

**Comment by JamXi233** [comment]
是否手动修改过Engine.ini或者使用了其他人的Engine.ini
文件位于[Wuthering Waves Game\Client\Saved\Config\WindowsNoEditor\Engine.ini]

**Comment by JamXi233** [comment]
已经超过两周没有收到您的回复，将关闭该issue。

**Comment by IshtarCC** [comment]
Engine.ini中若存在该项
