### ISSUE TITLE
[Bug?]账号切换器在未初始化时会阻挡开始游戏

### ISSUE THREAD

**Issue by TechOtakupoi233** [JamXi233/WaveTools#44]
## 问题描述
初次使用或清除数据后，直接点击启动游戏会提示未选择账号，需要先点击一次“仍要使用”再关闭功能才可以跳过账号选择器启动。
![image](https://github.com/user-attachments/assets/c3418673-05bd-4f5d-8fac-f37e7b85f2b2)

### 如何复现
初次安装或清除数据

### 预期表现
初次安装后不需要点击“仍要使用”便能直接启动游戏。

**Comment by JamXi233** [comment]
[WaveTools_1.1.6.0](https://github.com/JamXi233/WaveTools/releases/tag/1.1.6.0)已修复该功能
