### ISSUE TITLE
抽卡记录无法使用

### ISSUE THREAD

**Issue by Angelenx** [JamXi233/WaveTools#46]
点击获取抽卡记录没有可选的uid，登录游戏打开了抽卡记录页面也不行。

**Comment by JamXi233** [comment]
详见 #42

**Comment by JamXi233** [comment]
@AkatsukiZhang 重新获取抽卡记录试一下[建议先导出]

**Comment by AkatsukiZhang** [comment]
> @AkatsukiZhang 重新获取抽卡记录试一下[建议先导出]

清空记录重新获取后可以了。
