### ISSUE TITLE
无法解锁120帧

### ISSUE THREAD

**Issue by yangjun198907** [JamXi233/WaveTools#47]
不小心在游戏内修改了一下画质选项，帧数就锁死在60帧，在工具箱无论怎么修改都无法变回120帧  鸣潮版本1.2

**Comment by HyperCherry** [comment]
在此次的更新中，更改了对文件`LocalStorage.db`的定义，将`CustomFrameRate`单独作为了一个键，工具需要重新适配，可以参考
[此视频](https://www.bilibili.com/video/BV1FDe4eWEFm)临时使用
![image](https://github.com/user-attachments/assets/731b5397-a60e-49eb-b97a-1dbc9c69961c)

**Comment by JamXi233** [comment]
下一版本将会完成适配

**Comment by JamXi233** [comment]
[WaveTools_1.1.6.0](https://github.com/JamXi233/WaveTools/releases/tag/1.1.6.0)已完成适配新版本
