### ISSUE TITLE
导出抽卡记录报错

### ISSUE THREAD

**Issue by Heyawadu** [JamXi233/WaveTools#49]
[WaveTools_Panic_20240817_014253.zip](https://github.com/user-attachments/files/16639906/WaveTools_Panic_20240817_014253.zip)

**Comment by JamXi233** [comment]
是否使用Windows精简版本？

**Comment by Heyawadu** [comment]
> 是否使用Windows精简版本？

用的是从win11家庭版升级到的专业版

**Comment by Heyawadu** [comment]
> 是否使用Windows精简版本？

卸载重装WaveTools后导出正常
