### ISSUE TITLE
抽卡目前有抓到API或者具体的文件吗

### ISSUE THREAD

**Issue by LaoshuBaby** [JamXi233/WaveTools#5]
![图片](https://github.com/JamXi233/WaveTools/assets/42690037/d0d62727-c307-43b9-86d9-7baee275e8cb)
毕竟可能设计上确实有学习友商的经验，所以在想能否把友商的抽卡记录分析整理的工具链迁移到鸣潮这边来（目前全github搜到的鸣潮工具不多，有抽卡分析计划的就您一个）（ https://github.com/FxRayHughes/chaobot 可能也会有，但没找到）

**Comment by JamXi233** [comment]
**抽卡分析功能**将于下一小版本[WaveTools
_1.0.1.0]推出，大概26日或27日这样。将会有两种模式，一种是正常的抽卡分析模式。另一种是Web模式(就如您图片中一样，在工具箱中可快速打开官方抽卡记录)。
正常的抽卡分析模式与[SRTools](https://github.com/JamXi233/SRTools)中的抽卡分析功能基本一致。

**Comment by LaoshuBaby** [comment]
> 正常的抽卡分析模式与[SRTools](https://github.com/JamXi233/SRTools)中的抽卡分析功能基本一致。

?!啊原来这个也是您的啊（抱歉光记得工具名第一反应没认出作者来（草我这次就是一看有新开服而且昨天抓了点包试试发现非常邪门觉得可以和星穹铁道开服的时候一样聚集起来搞搞可交换（好好好

说实话它这个Web居然是可以直接在网页端访问的还是真没想到

本来是打算今天拿py搓一点工具的，不过既然这样就不重复造轮子了

**Comment by JamXi233** [comment]
[WaveTools_1.1.0.0](https://github.com/JamXi233/WaveTools/releases/tag/WaveTools_1.1.0.0)
已添加抽卡分析功能
