### ISSUE TITLE
无法更新依赖

### ISSUE THREAD

**Issue by honestman9981** [JamXi233/WaveTools#51]
今天不是提示更新吗 无法正常更新依赖
重装了也不行
请问有下载安装的方法吗

**Comment by Cihua9102** [comment]
我同样出现了这样的问题：

[INFO]UpdateService:JSG-DS
[INFO]Software Name:WaveToolsHelper
[INFO]Newer Version:1.2.4.0
[ERROR]运行安装程序时出错: An error occurred trying to start process 'C:\Users\cihua\Documents\JSG-LLC\WaveTools\Installer\WaveToolsInstaller.exe' with working directory 'C:\Windows\system32'. The specified executable is not a valid application for this OS platform.

**Comment by NooAcc** [comment]
在作者修复之前临时的解决办法：
1、下载[WaveToolsHelper_1.2.4.0](https://github.com/JamXi233/Releases/releases/download/WaveToolsHelper_1.2.4.0/WaveToolsHelper_1.2.4.0.zip)
2、解压覆盖到 C:\Users\用户名\Documents\JSG-LLC\WaveTools\Depends\WaveToolsHelper 文件夹

**Comment by honestman9981** [comment]
截止刚刚，能正常检查更新依赖了，并且已经更新成功

**Comment by JamXi233** [comment]
@Cihua9102
可能是当时服务器出现了一些问题，目前可以正常工作。请再试一次。
