### ISSUE TITLE
powershell安装不了，一直卡在0.03%

### ISSUE THREAD

**Issue by zxygzxy** [JamXi233/WaveTools#54]
如图
![QQ截图20240825140218](https://github.com/user-attachments/assets/bf689117-a660-4bc3-b88f-3817ffec4516)

**Comment by JamXi233** [comment]
连接到微软的网络太慢
可使用JSG-DS下载
[windowsdesktop-runtime-7.0.15-win-x64.exe](https://ds.jamsg.cn/d/Release/Runtime/windowsdesktop-runtime-7.0.15-win-x64.exe)
下载后需要手动安装
安装完成后再次使用Powershell安装会自动跳过运行库安装。
