### ISSUE TITLE
请求，同步一下官方启动器的DX12和因特尔显卡Xess设置项

### ISSUE THREAD

**Issue by 2103894869** [JamXi233/WaveTools#56]
请求，同步一下官方启动器的DX12和因特尔显卡Xess设置项
![image](https://github.com/user-attachments/assets/d1b0273b-cd52-4cf7-82b0-acaa1923cd79)

**Comment by JamXi233** [comment]
[WaveTools_1.1.7.0](https://github.com/JamXi233/WaveTools/releases/tag/1.1.7.0)已添加功能
