### ISSUE TITLE
游戏更新后无法获取抽卡记录

### ISSUE THREAD

**Issue by Kakitoritay** [JamXi233/WaveTools#59]
![20240929181602](https://github.com/user-attachments/assets/2131f6e6-71d2-4890-be27-6bea467d4d36)

**Comment by JamXi233** [comment]
是否修改过Engine.ini文件?

**Comment by Kakitoritay** [comment]
是的，使用了https://github.com/AlteriaX/WuWa-Configs的配置

**Comment by Kakitoritay** [comment]
恢复默认Engine.ini文件恢复正常了，谢谢大佬

**Comment by XFFF2022** [comment]
这是由于 **Engine.ini** 包含以下（或者类似）配置导致的。
这个配置关闭了日志，导致 **WaveTools** 无法获取抽卡记录
```ini
[Core.Log]
global=none
```
