### ISSUE TITLE
无法获取记录，提示需要更新，但是无法更新

### ISSUE THREAD

**Issue by zxygzxy** [JamXi233/WaveTools#61]
如标题
![QQ截图20241002152841](https://github.com/user-attachments/assets/182cb0a7-3adb-456f-b1e4-ec014329668e)
![QQ截图20241002152851](https://github.com/user-attachments/assets/290f7509-5c5e-4ee2-8672-c6eb9509f867)
![QQ截图20241002152859](https://github.com/user-attachments/assets/3e2ad689-251e-4b25-9bdb-fac50c73aba5)
![QQ截图20241002152912](https://github.com/user-attachments/assets/2c66cd93-6adf-451d-b65e-7b2ad403d511)

**Comment by JamXi233** [comment]
SSL证书到期，现已修复。
