### ISSUE TITLE
抽卡记录无法导出，导出报错

### ISSUE THREAD

**Issue by easyinplay** [JamXi233/WaveTools#62]
![image](https://github.com/user-attachments/assets/a6ba0b32-c859-406d-a490-52f924d979c2)
[WaveTools_Panic_20241018_222709.zip](https://github.com/user-attachments/files/17436935/WaveTools_Panic_20241018_222709.zip)

附近为日志文件

**Comment by JamXi233** [comment]
官方的系统还是精简版的系统

**Comment by TomyJan** [comment]
[Panic.zip](https://github.com/user-attachments/files/17514233/Panic.zip)
同样的问题, 导入导出都报错, 官方系统 win11 23H2

**Comment by JamXi233** [comment]
已经确认问题所在，当使用管理员身份运行(状态为Privileged)时大概率会出现该问题。
将在下一版本修复该问题。

**Comment by JamXi233** [comment]
[WaveTools_1.1.8.0](https://github.com/JamXi233/WaveTools/releases/tag/1.1.8.0)已修复该问题
