### ISSUE TITLE
无法获取抽卡记录

### ISSUE THREAD

**Issue by mz3571248** [JamXi233/WaveTools#64]
![1729754849674](https://github.com/user-attachments/assets/71a938aa-2fc4-4c11-9757-125a8927e13c)

**Comment by mz3571248** [comment]
![1729754849674](https://github.com/user-attachments/assets/2a004bfc-ab48-47a8-8568-148575b594e5)

**Comment by JamXi233** [comment]
可以先看一下#59

**Comment by mz3571248** [comment]
> 可以先看一下#59

已解决！
