### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by BAYUNZIYUE** [JamXi233/WaveTools#66]
__          __          _______          _      _____           _        _ _
 \ \        / /         |__   __|        | |    |_   _|         | |      | | |  v1.0.2.0
  \ \  /\  / /_ ___   _____| | ___   ___ | |___   | |  _ __  ___| |_ __ _| | | ___ _ __
   \ \/  \/ / _` \ \ / / _ \ |/ _ \ / _ \| / __|  | | | '_ \/ __| __/ _` | | |/ _ \ '__|
    \  /\  / (_| |\ V /  __/ | (_) | (_) | \__ \ _| |_| | | \__ \ || (_| | | |  __/ |
     \/  \/ \__,_| \_/ \___|_|\___/ \___/|_|___/|_____|_| |_|___/\__\__,_|_|_|\___|_|
──────────────────────────────────────────────────────────────────────────────────────────
[INFO]WaveTools 已安装，当前版本为：1.1.7.0
[INFO]获取到的最新版本号为：1.1.7.0
[INFO]已安装的版本是最新的，无需更新。
──────────────────────────────────────────────────────────────────────────────────────────

🕘  安装提前结束,按任意键退出

**Comment by JamXi233** [comment]
已经修复
