### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by zzl2008520** [JamXi233/WaveTools#67]
无法更新，提示.resources\cs-CZ”的访问被拒绝。

![293C4F1D8925211C3EC7BE83F5D1A776](https://github.com/user-attachments/assets/cebdd14f-2831-40d4-a081-7a11fab9cfb2)

**Comment by JamXi233** [comment]
**请检查权限问题**
看起来您在使用OneDrive作为文档目录，可能会导致不可预料的错误。
