### ISSUE TITLE
获取卡池信息时发生错误

### ISSUE THREAD

**Issue by CharlotteHN** [JamXi233/WaveTools#68]
![93b545bb32f7feb6e4a0de7121909166](https://github.com/user-attachments/assets/ddb81976-badf-4425-b178-67937cb0c952)
[](url)
[WaveTools_Panic_20241106_113030.zip](https://github.com/user-attachments/files/17641330/WaveTools_Panic_20241106_113030.zip)

点击抽象信息界面就会弹出图中报错，自动生成的错误报告打包上传了，麻烦看看。

**Comment by JamXi233** [comment]
目前服务器正在维护，预计16:00完成维护。

**Comment by CharlotteHN** [comment]
好的，感谢！
