### ISSUE TITLE
安装后启动报错

### ISSUE THREAD

**Issue by cenbide** [JamXi233/WaveTools#7]
![a5994652-8980-4ae9-9499-61c337694f9a](https://github.com/JamXi233/WaveTools/assets/49063453/b14fdfad-d87d-4281-a872-c53ae2886bf2)
![image](https://github.com/JamXi233/WaveTools/assets/49063453/7b601e3a-c9b2-4402-a52d-329f421dd01f)
![image](https://github.com/JamXi233/WaveTools/assets/49063453/3a78cddc-95c8-4fa9-940c-b88990db2065)

安装后打开报错，

**Comment by JamXi233** [comment]
请通过此邮箱联系我[jamsg@qq.com]
原因:无法复现该问题
