### ISSUE TITLE
作者您好，我使用管理员权限用Powershell安装程序出现报错并自动关闭了Powershell，使用压缩包安装时出现了0x800B0101a的证书问题，我该如何解决

### ISSUE THREAD

**Issue by DZCOFE** [JamXi233/WaveTools#71]
![443b7aa4-cbc1-467b-af3f-f5fd1ccd4e0a](https://github.com/user-attachments/assets/bf2524d9-0043-47f8-b8ad-ff632304f2df)

**Comment by JamXi233** [comment]
请再次尝试使用Powershell进行安装

**Comment by DZCOFE** [comment]
谢谢，已解决
