### ISSUE TITLE
打开wavetools时显示游戏已运行

### ISSUE THREAD

**Issue by yangjun198907** [JamXi233/WaveTools#76]
打开wavetools时显示游戏已运行，但是实际游戏并未运行，只能通过启动器打开游戏
![Uploading 微信截图_20241217123117.png…]()

**Comment by JamXi233** [comment]
图片没有上传成功
重启电脑后启动工具箱也会显示游戏已运行吗?

**Comment by yangjun198907** [comment]
今天重新打开后正常了，应该是我这边电脑的问题，感谢作者回复
