### ISSUE TITLE
 xmlns:local="using:WaveTools">

### ISSUE THREAD

**Issue by 10176137** [JamXi233/WaveTools#8]
我编译的时候ApplicationDataContainer localSettings = ApplicationData.Current.LocalSettings;赋值出错，我看了一下app.xaml，xmlns:local="using:WaveTools"显示local不必要的

**Comment by JamXi233** [comment]
如果您遇到了什么问题，请描述您的问题。
https://github.com/JamXi233/SRTools/issues/25
