### ISSUE TITLE
1.1.0.0版本 检查依赖更新用不了，获取抽卡记录失败

### ISSUE THREAD

**Issue by YuSidesu** [JamXi233/WaveTools#9]
更新后和重新下载都不能用
![1](https://github.com/JamXi233/WaveTools/assets/171003465/8cabe9d9-c97a-4044-9218-d17b80c5fcbd)
![2](https://github.com/JamXi233/WaveTools/assets/171003465/ae120fe9-d3ba-4881-b456-828efdd17b93)
![3](https://github.com/JamXi233/WaveTools/assets/171003465/3f8e9167-6380-4faf-bb53-aefa3a4d9d0b)

**Comment by JamXi233** [comment]
看一下
https://api.jamsg.cn/
是否可以进入

**Comment by JamXi233** [comment]
### 尝试使用Powershell强制更新WaveToolsHelper
在Powershell输入`irm wavetools.jamsg.cn/get | iex`
点击回车后**立即按住Shift键**直到出现[高级模式]
选择[强制覆盖安装WaveToolsHelper]然后点击回车
重新启动WaveTools再试一下

**Comment by YuSidesu** [comment]
可以了谢谢

**Comment by JamXi233** [comment]
目前软件内更新依赖/更新SRTools存在问题，将会在下一版本修复
